### Update a Meme (Change Image)
PUT http://localhost:3000/api/memes/6
Content-Type: application/json

{
    "image": "new-meme6.jpg"
}

### Update a Caption (Change Text and Points)
PUT http://localhost:3000/api/captions/1
Content-Type: application/json

{
    "text": "Testing",
    "points": 15
}
